[[constraint]]
  branch = "master"
  name = "github.com/4thokage/go-devinfo"

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.1"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.4"

[[constraint]]
  name = "go.mongodb.org/mongo-driver"
  version = "1.3.2"

[prune]
  go-tests = true
  unused-packages = true
