/*
 * JSR Info
 *
 * This is an API server for a developer web portfolio. Used @jose-rodrigues.info
 *
 * API version: 1.0.0
 * Contact: jsr@jose-rodrigues.info
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"net/http"

	sw "github.com/4thokage/go-devinfo/api"
	"github.com/4thokage/go-devinfo/config"
)

// Initializes the configuration and starts the server
func main() {
	var conf config.Config

	conf.Read()

	// listen on configured port
	log.Fatal(http.ListenAndServe(":"+conf.Port, sw.NewRouter()))
}
