/*
 * JSR Info
 *
 * This is an API server for a developer web portfolio. Used @jose-rodrigues.info
 *
 * API version: 1.0.0
 * Contact: jsr@jose-rodrigues.info
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

import (
	"encoding/json"
	"net/http"
)

// GetJobs returns all the jobs of the developer
func GetJobs(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.Header().Set("Access-Control-Allow-Origin", "*")

	payload := GetAllJobs()

	_ = json.NewEncoder(w).Encode(payload)
}
