/*
 * JSR Info
 *
 * This is an API server for a developer web portfolio. Used @jose-rodrigues.info
 *
 * API version: 1.0.0
 * Contact: jsr@jose-rodrigues.info
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Project represents a personal project made by the developer
type Project struct {

	// the project name
	Name string `json:"name"`

	// a short summary of the project
	Description string `json:"description"`

	// image url
	ImageURL string `json:"imageURL,omitempty"`

	// github url
	GitURL string `json:"gitURL"`
}
