/*
 * JSR Info
 *
 * This is an API server for a developer web portfolio. Used @jose-rodrigues.info
 *
 * API version: 1.0.0
 * Contact: jsr@jose-rodrigues.info
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Job represents a job the developer has or had
type Job struct {

	// job description (tech stack, functions that the developer was responsible for, etc)
	Description string `json:"description"`

	// Company (url) in which the developer worked while doing this job
	Company string `json:"company"`

	// the start date of the job (ISO 8601)
	StartDate string `json:"startDate"`

	// the end date of the job (ISO 8601)
	EndDate string `json:"endDate,omitempty"`
}
